# Generated by Django 5.1.4 on 2025-01-07 21:46

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1960), cars.models.max_value_current_year]),
        ),
    ]
